server:
  port: 9101
  
spring:
  application:
    name: config
  cloud:
    config:
      enabled: true
      server:
        git:
          uri: git@github.com:Bishem/commerce-configs.git